urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import redirect_to
from django.contrib import admin
from django_openid.registration import RegistrationConsumer
from articles.views import starting_page
import settings


admin.autodiscover()


urlpatterns = patterns('',
    (r'^$', starting_page),
    (r'^articles/', include('articles.urls')),
    (r'^proposals/', include('proposals.urls')),
    (r'^changes/', include('changes.urls')),
    (r'^comments/', include('comments.urls')),
    (r'^profiles/', include('profiles.urls')),
    (r'^openid/(.*)', RegistrationConsumer()),
    (r'^admin/(.*)', admin.site.root),
)


if settings.DEBUG:
    urlpatterns += patterns('', 
        (r'^static_media/(?P<path>.*)$', 'django.views.static.serve', 
                    {'document_root': settings.MEDIA_ROOT }),)

django_openid/models.py
from django.db import models
from django.conf import settings
from django.utils.hashcompat import md5_constructor
from openid.store.interface import OpenIDStore
import openid.store
from openid.association import Association as OIDAssociation
import time, base64

class Nonce(models.Model):
    server_url = models.CharField(max_length=255)
    timestamp = models.IntegerField()
    salt = models.CharField(max_length=40)
    
    def __unicode__(self):
        return u"Nonce: %s for %s" % (self.salt, self.server_url)

class Association(models.Model):
    server_url = models.TextField(max_length=2047)
    handle = models.CharField(max_length=255)
    secret = models.TextField(max_length=255) # Stored base64 encoded
    issued = models.IntegerField()
    lifetime = models.IntegerField()
    assoc_type = models.TextField(max_length=64)
    
    def __unicode__(self):
        return u"Association: %s, %s" % (self.server_url, self.handle)

class DjangoOpenIDStore(OpenIDStore):
    """
    The Python openid library needs an OpenIDStore subclass to persist data 
    related to OpenID authentications. This one uses our Django models.
    """
    
    def storeAssociation(self, server_url, association):
        assoc = Association(
            server_url = server_url,
            handle = association.handle,
            secret = base64.encodestring(association.secret),
            issued = association.issued,
            lifetime = association.issued,
            assoc_type = association.assoc_type
        )
        assoc.save()
    
    def getAssociation(self, server_url, handle=None):
        assocs = []
        if handle is not None:
            assocs = Association.objects.filter(
                server_url = server_url, handle = handle
            )
        else:
            assocs = Association.objects.filter(
                server_url = server_url
            )
        if not assocs:
            return None
        associations = []
        for assoc in assocs:
            association = OIDAssociation(
                assoc.handle, base64.decodestring(assoc.secret), assoc.issued,
                assoc.lifetime, assoc.assoc_type
            )
            if association.getExpiresIn() == 0:
                self.removeAssociation(server_url, assoc.handle)
            else:
                associations.append((association.issued, association))
        if not associations:
            return None
        return associations[-1][1]
    
    def removeAssociation(self, server_url, handle):
        assocs = list(Association.objects.filter(
            server_url = server_url, handle = handle
        ))
        assocs_exist = len(assocs) > 0
        for assoc in assocs:
            assoc.delete()
        return assocs_exist
    
    def useNonce(self, server_url, timestamp, salt):
        # Has nonce expired?
        if abs(timestamp - time.time()) > openid.store.nonce.SKEW:
            return False
        try:
            nonce = Nonce.objects.get(
                server_url__exact = server_url,
                timestamp__exact = timestamp,
                salt__exact = salt
            )
        except Nonce.DoesNotExist:
            nonce = Nonce.objects.create(
                server_url = server_url,
                timestamp = timestamp,
                salt = salt
            )
            return True
        nonce.delete()
        return False
    
    def cleanupNonce(self):
        Nonce.objects.filter(
            timestamp__lt = (int(time.time()) - nonce.SKEW)
        ).delete()
    
    def cleaupAssociations(self):
        Association.objects.extra(
            where=['issued + lifetimeint < (%s)' % time.time()]
        ).delete()
    
    def getAuthKey(self):
        # Use first AUTH_KEY_LEN characters of md5 hash of SECRET_KEY
        return md5_constructor.new(settings.SECRET_KEY).hexdigest()[:self.AUTH_KEY_LEN]
    
    def isDumb(self):
        return False

# Only include table for User->OpenID associations if User model is installed
user_model = models.get_model('auth', 'User')
if user_model and user_model._meta.installed:
    class UserOpenidAssociation(models.Model):
        "Auth integration - lets you associate 1+ OpenIDs with a User"
        user = models.ForeignKey('auth.User', related_name = 'openids')
        openid = models.CharField(max_length = 255)
        created = models.DateTimeField(auto_now_add = True)
        
        def __unicode__(self):
            return u'%s can log in with %s' % (self.user, self.openid)

django_openid/forms.py
from django.contrib.auth.models import User
from django import forms

import re

class RegistrationForm(forms.ModelForm):
    no_password_error = 'You must either set a password or attach an OpenID'
    invalid_username_error = 'Usernames must consist of letters and numbers'
    reserved_username_error = 'That username cannot be registered'
    duplicate_email_error = 'That e-mail address is already in use'
    
    username_re = re.compile('^[a-zA-Z0-9]+$')
    
    # Additional required fields (above what the User model says)
    extra_required = ('first_name', 'last_name', 'email')
    
    def __init__(self, *args, **kwargs):
        """
        Accepts openid as optional keyword argument, for password validation.
        Also accepts optional reserved_usernames keyword argument which is a
        list of usernames that should not be registered (e.g. 'security')
        """
        try:
            self.openid = kwargs.pop('openid')
        except KeyError:
            self.openid = None
        try:
            self.reserved_usernames = kwargs.pop('reserved_usernames')
        except KeyError:
            self.reserved_usernames = []
        try:
            self.no_duplicate_emails = kwargs.pop('no_duplicate_emails')
        except KeyError:
            self.no_duplicate_emails = False
        
        # Super's __init__ creates self.fields for us
        super(RegistrationForm, self).__init__(*args, **kwargs)
        # Now we can modify self.fields with our extra required information
        for field in self.extra_required:
            self.fields[field].required = True
    
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')
    
    # Password is NOT required as a general rule; we only validate that they 
    # have set a password if an OpenID is not being associated
    password = forms.CharField(
        widget = forms.PasswordInput,
        required = False
    )
    
    def clean_username(self):
        username = self.cleaned_data.get('username', '')
        if not self.username_re.match(username):
            raise forms.ValidationError, self.invalid_username_error
        if username in self.reserved_usernames:
            raise forms.ValidationError, self.reserved_username_error
        return username
    
    def clean_password(self):
        "Password is only required if no OpenID was specified"
        password = self.cleaned_data.get('password', '')
        if not self.openid and not password:
            raise forms.ValidationError, self.no_password_error
        return password
    
    def clean_email(self):
        email = self.cleaned_data.get('email', '')
        if self.no_duplicate_emails and User.objects.filter(
            email = email
        ).count() > 0:
            raise forms.ValidationError, self.duplicate_email_error
        return email

class RegistrationFormPasswordConfirm(RegistrationForm):
    password_mismatch_error = 'Your passwords do not match'
    
    password2 = forms.CharField(
        widget = forms.PasswordInput,
        required = False,
        label = "Confirm password"
    )
    
    def clean_password2(self):
        password = self.cleaned_data.get('password', '')
        password2 = self.cleaned_data.get('password2', '')
        if password and (password != password2):
            raise forms.ValidationError, self.password_mismatch_error
        return password2

class ChangePasswordForm(forms.Form):
    password = forms.CharField(
        widget = forms.PasswordInput,
        required = True
    )
    password2 = forms.CharField(
        widget = forms.PasswordInput,
        required = True,
        label = 'Confirm password'
    )
    password_mismatch_error = 'Your passwords do not match'
    
    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(ChangePasswordForm, self).__init__(*args, **kwargs)
    
    def clean_password2(self):
        password = self.cleaned_data.get('password', '')
        password2 = self.cleaned_data.get('password2', '')
        if password and (password != password2):
            raise forms.ValidationError, self.password_mismatch_error
        return password2

class ChangePasswordVerifyOldForm(ChangePasswordForm):
    """
    Use this if you want the user to enter their old password first
    
    Careful though... if hte user has just recovered their account, they
    should be able to reset their password without having to enter the old
    one. This case is not currently handled.
    """
    password_incorrect_error = 'Your password is incorrect'
    
    def __init__(self, *args, **kwargs):
        super(ChangePasswordVerifyOldForm, self).__init__(*args, **kwargs)
        if self.user.has_usable_password() and self.user.password:
            # Only ask for their old password if they have set it already
            self.fields['old_password'] = forms.CharField(
                widget = forms.PasswordInput,
                required = True
            )
    
    def clean_old_password(self):
        password = self.cleaned_data.get('old_password', '')
        if not self.user.check_password(password):
            raise forms.ValidationError, self.password_incorrect_error

django_openid/templates/django_openid/_register_form_field.html
<div class="field-wrapper{% if field.errors %} errors{% endif %}">
    {{ field.errors }}
    {{ field.label_tag }} {{ field }}
</div>

django_openid/templates/django_openid/admin_login.html
{% extends "admin/base_site.html" %}
{% load i18n %}

{% block stylesheet %}{% load adminmedia %}{% admin_media_prefix %}css/login.css{% endblock %}

{% block bodyclass %}login{% endblock %}

{% block content_title %}{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block content %}
{% if error_message %}
<p class="errornote">{{ error_message }}</p>
{% endif %}
<div id="content-main">
<p>{% trans 'Log in with your username and password:' %}</p>
<form action="{{ app_path }}" method="post" id="login-form">
  <div class="form-row">
    <label for="id_username">{% trans 'Username:' %}</label> <input type="text" name="username" id="id_username" />
  </div>
  <div class="form-row">
    <label for="id_password">{% trans 'Password:' %}</label> <input type="password" name="password" id="id_password" />
    <input type="hidden" name="this_is_the_login_form" value="1" />
    <input type="hidden" name="post_data" value="{{ post_data }}" />
  </div>
  <div class="submit-row">
    <label>&nbsp;</label><input type="submit" value="{% trans 'Log in' %}" />
  </div>
</form>
<p>{% trans 'Or use your OpenID:' %}</p>
<form action="{{ openid_path }}" method="post" id="openid-login-form">
  <div class="form-row">
    <label for="id_openid"><img src="{{ openid_path }}logo/" alt=""> {% trans 'OpenID:' %}</label> <input type="text" name="openid_url" id="id_openid" />
  </div>
  <div class="submit-row">
    <label>&nbsp;</label><input type="submit" value="{% trans 'Log in with OpenID' %}" />
  </div>
</form>


<script type="text/javascript">
document.getElementById('id_username').focus()
</script>
</div>
{% endblock %}

django_openid/templates/django_openid/already_logged_in.html
{% extends base_template %}

{% block title %}You are already logged in{% endblock %}

{% block content %}
<h1>You are already logged in</h1>

<p>Log out before trying to log in using another account.</p>

{% endblock %}

django_openid/templates/django_openid/associate.html
{% extends base_template %}

{% block title %}Associate with your account?{% endblock %}

{% block content %}
<h1>Associate with your account?</h1>

<p>Do you wish to associate <strong>{{ specific_openid }}</strong> with your account? This will allow you to sign in as <strong>{{ user }}</strong> using that OpenID.</p>

<form action="{{ action }}" method="post">
<p>
    <input type="hidden" name="openid_token" value="{{ openid_token }}">
{% if next %}    <input type="hidden" name="next" value="{{ next }}">
{% endif %}    <input type="submit" value="Associate">
</p>
</form>
{% endblock %}

django_openid/templates/django_openid/associations.html
{% extends base_template %}

{% block title %}Manage your associated OpenIDs{% endblock %}

{% block content %}
<h1>Manage your associated OpenIDs</h1>

<p>You have {{ openids|length }} OpenID{{ openids|length|pluralize}} associated with your account.</p>

{% if message %}<p><strong>{{ message }}</strong></p>{% endif %}

{% for openid in openids %}
<form action="{{ action }}" method="POST">
    <p>{{ openid.openid }}
        <input type="hidden" name="todelete" value="{{ openid.button }}">
        <input id="delete-{{ forloop.counter }}" type="submit" value="Delete this association">
    </p>
</form>
{% endfor %}

<p><strong>Associate a new OpenID:</strong></p>

<form action="{{ action_new }}" method="post">
<p>
    <input class="openid" type="text" name="openid_url">
    <input type="hidden" name="next" value="{{ associate_next }}">
    <input type="submit" value="Associate">
</p>
</form>

{% endblock %}

django_openid/templates/django_openid/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
  "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<title>{% block title %}Sign in with your OpenID{% endblock %}</title>
<style type="text/css">
body {
    margin: 2em;
    font-family: georgia;
}
h1, h2 {
    border-bottom: 1px solid #666;
    padding-bottom: 0.2em;
}
ul.errorlist {
    margin: 0;
    padding: 0.2em 0.4em;
    background-color: red;
    color: white;
    list-style-type: none;
}
</style>
{% block extra_head %}{% endblock %}
</head>
<body>
{% block content %}

{% endblock %}
</body>
</html>

django_openid/templates/django_openid/decide.html
{% extends base_template %}

{% block title %}Sign in?{% endblock %}

{% block content %}
<h1>Sign in?</h1>

<p>Sign in to <strong>{{ trust_root }}</strong> as <strong>{{ identity }}</strong>?</p>

<form action="{{ action }}" method="POST">
    <p>
        {% if save_trusted_roots %}
        <input type="submit" name="yes_once" value="Yes, just this once">
        <input type="submit" name="yes_always" value="Yes, always">
        {% else %}
        <input type="submit" name="yes_once" value="Log in now">
        {% endif %}
        <input type="hidden" name="_decide" value="1">
        <input type="hidden" name="orequest" value="{{ orequest }}">
    </p>
</form>
{% endblock %}

django_openid/templates/django_openid/login_old.html
{% extends 'base.html' %}
{% load i18n %}


{% block content %}
    <form id="openid_form" action="{{ action }}" method="post"  style="margin: 0.5em 0 0;">
        <fieldset>
            <label for="id_openid_identifier">
                {% blocktrans %}
                    If you'd like to register, or if you've already
                    registered, enter your OpenID
                {% endblocktrans %}
            </label>
            <br/>
            <br/>
            {{ form.openid_identifier }}
            <input name="bsignin" type="submit" value="Sign in">

            {% if next %}
                <input type="hidden" name="next" value="{{ next }}" />
            {% endif %}
        </fieldset>
    </form>	
    <div id="openid_shortcuts">
        {% blocktrans %}
            Alternately, click your account provider:
        {% endblocktrans %}
        <br/>
        <br/>
        <a id="openid" class="openid" style="background: url(/static_media/openid/openid.png) no-repeat center center;"></a>
        <a id="google" class="openid" style="background: url(/static_media/openid/google.png) no-repeat center center;"/></a>
        <a id="yahoo"  class="openid" style="background: url(/static_media/openid/yahoo.png) no-repeat center center;"/></a>
        <a id="aol"    class="openid" style="background: url(/static_media/openid/aol.png) no-repeat center center;"/></a>

        <div class="clearer"></div>
        <br/>
        <br/>
        <img id="myopenid"      class="s_openid" src="/static_media/openid/myopenid.png" title="MyOPenID"/>
        <img id="livejournal"   class="s_openid" src="/static_media/openid/livejournal.png" title="LiveJournal"/>
        <img id="flickr"        class="s_openid" src="/static_media/openid/flickr.png" title="Flickr"/>
        <img id="technorati"    class="s_openid" src="/static_media/openid/technorati.png" title="Technorati"/>
        <img id="wordpress"     class="s_openid" src="/static_media/openid/wordpress.png" title="WordPress"/>
        <img id="blogger"       class="s_openid" src="/static_media/openid/blogger.png" title="Blogger"/>
        <img id="verisign"      class="s_openid" src="/static_media/openid/verisign.png" title="Verisign"/>
        <img id="vidoop"        class="s_openid" src="/static_media/openid/vidoop.png" title="Vidoop"/>
        <img id="claimid"       class="s_openid" src="/static_media/openid/claimid.png" title="Claimid"/>

        <div id="openid_userid">
            <label id="openid_label">{% trans "enter your openid" %}</label><br/>
            <input id="openid_user" type="text" size="40" maxlength="255" name="openis_user"/>
            <button id="openid_signin"> {% trans "Sign in" %} </button>
        </div>

    </div>

    <div class="info_box">
        {% blocktrans %}
            <p><b>Info OpenID</b><br/>
            OpenID eliminates the need for multiple usernames across different
            websites, simplifying your online experience.
            </p>
            <p>You get to choose the OpenID Provider that best meets your
            needs and most importantly that you trust. At the same time,
            your OpenID can stay with you, no matter which Provider you
            move to. And best of all, the OpenID technology is not
            proprietary and is completely free.
            </p>

            <p>You can use OpenIDs from any provider. If you don't have
            already an OpenID you can find a provider in this 
            <a href="http://openid.net/get/">provider list</a>.</p>

            <p>To create an OpenID for a test user, you can use this 
            <a href="https://openid.radamanthys.de/">site</a>, but this OpenID
            not reliable for general use.
            </p>
        {% endblocktrans %}
    </div>
{% endblock %}
{% block scripts %}
<script type="text/javascript" src="/static_media/candiwi_openid.js"></script>
{% endblock %}

django_openid/templates/django_openid/message.html
{% extends base_template %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<h1>{{ title }}</h1>

<p>{{ message }}</p>
{% endblock %}

django_openid/templates/django_openid/pick_account.html
{% extends base_template %}

{% block title %}Which account would you like?{% endblock %}

{% block content %}
<h1>Which account would you like?</h1>

<p>The OpenID <strong>{{ openid }}</strong> is associated with {{ users|length }} different accounts. Which user do you wish to sign in as?</p>

<form action="{{ action }}" method="POST">
{% for user in users %}
    <p><input type="submit" name="user-{{ user.id }}" value="{{ user }}"></p>
{% endfor %}
</form>

{% endblock %}

django_openid/templates/django_openid/recover.html
{% extends base_template %}

{% block title %}Recover your account{% endblock %}

{% block content %}
<h1>Can't log in?</h1>

{% if message %}
<p>{{ message }}</p>
{% endif %}

<p>Enter your username or e-mail address and we'll send you a link to recover your account.</p>

<form action="{{ action }}" method="post">
<p>
    <label for="id_recover">Username / E-mail:</label> <input id="id_recover" type="text" name="recover"> <input type="submit" value="Recover account">
</p>
</form>
{% endblock %}

django_openid/templates/django_openid/recovery_complete.html
{% extends base_template %}

{% block title %}Account recovered{% endblock %}

{% block content %}
<h2>Account recovered</h2>

<p>You are now logged in as <strong>{{ user }}</strong></p>

<ul>
    <li><a href="{{ change_password_url }}">Reset your password</a></li>
    <li><a href="{{ associate_url }}">Associate an OpenID with your account</a></li>
</ul>
{% endblock %}

django_openid/templates/django_openid/register.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}Register an account{% endblock %}


{% block content %}
    <h1>Register an account</h1>

    <h2>Enter your details</h2>
    <form action="{{ action }}" method="post">
        {% with form.username as field %}
            {% include "django_openid/_register_form_field.html" %}
        {% endwith %}
        {% with form.first_name as field %}
            {% include "django_openid/_register_form_field.html" %}
        {% endwith %}
        {% with form.last_name as field %}
            {% include "django_openid/_register_form_field.html" %}
        {% endwith %}
        {% with form.email as field %}
            {% include "django_openid/_register_form_field.html" %}
        {% endwith %}
        <div class="field-wrapper">
            <label for="id_voting" title="{% blocktrans %}Email me when a proposal enters into the voting period.{% endblocktrans %}">
            {% trans "Voting Mail" %}</label>
            <input id="id_voting" type="checkbox" name="voting_mail" checked="checked"></input>
        </div>
        <p><input type="submit" value="Register"></input></p>
    </form>
    <p>Your OpenID <strong>{{ openid }}</strong> will be associated with this account.</p>

{% endblock %}

django_openid/templates/django_openid/set_password.html
{% extends base_template %}

{% block title %}Set a password{% endblock %}

{% block extra_head %}
<style type="text/css">
input.openid {
  background: url({{ logo }}) no-repeat; 
  background-position: 0 50%;
  padding-left: 16px;
  width: 20em;
}
div.field-wrapper {
    clear: both;
    margin-bottom: 0.5em;
    width: 32em;
}
.errors input {
    background-color: pink;
}
div.field-wrapper label {
    width: 9em;
    float: left;
    clear: left;
}
div.field-wrapper input {
    width: 20em;
}
input#id_username {
    width: 12em;
}
</style>
{% endblock %}

{% block content %}
<h1>Set a password</h1>

{% if message %}
<p>{{ message }}</p>
{% endif %}

<p>You can optionally set a password on your account, to provide an alternative mechanism of logging in.</p>

<form action="{{ action }}" method="POST">
{% if form.old_password %}
{% with form.old_password as field %}{% include "django_openid/_register_form_field.html" %}{% endwith %}
{% endif %}
{% with form.password as field %}{% include "django_openid/_register_form_field.html" %}{% endwith %}
{% with form.password2 as field %}{% include "django_openid/_register_form_field.html" %}{% endwith %}
<p><input type="submit" value="Set password"></p>
</form>

{% endblock %}